### PR TITLE
Properly calculate cgroup cpu limits.

### PR DESCRIPTION
**Pull request by michaelfinch**
Cgroups are organized hierarchically. If a child does not have a cgroup cpu limit, we should check its parent(s) until we find a limit set. If no limit is set anywhere in the hierarchy, the cgroup is unrestricted.

### Testing
There aren't any tests for this package right now. I spent an hour trying to add some, but was unable to get them to run on my mac or in a linux docker container due to cross-platform compatibility errors. I'm confident this change should work, but if you'd like me to figure out how to add tests then I can do that.

### CODE REVIEW

**Review by akutta — CHANGES_REQUESTED** [review]
Instead of recursively looking through the file structure, thoughts on starting at the service level ( example: /sys/fs/cgroup/cpu,cpuacct/p2/<host>/<service>/cpu.* ) and create a service limit metric instead?

We can then leverage that as both a new metric and a max value for each launchable.

**Comment by michaelfinch** [comment]
> Instead of recursively looking through the file structure, thoughts on starting at the service level ( example: /sys/fs/cgroup/cpu,cpuacct/p2///cpu.* ) and create a service limit metric instead?
> 
> We can then leverage that as both a new metric and a max value for each launchable.

We could do that, but I'm wondering if the additional complexity is worth it. Adding a new metric won't be useful unless we then update all of the detectors that attempt to look at the cpu limit of a launchable. If instead we just fix the metric that everyone is already using, we won't have to update any detectors and they will start working as expected.

**Comment by akutta** [comment]
> > Instead of recursively looking through the file structure, thoughts on starting at the service level ( example: /sys/fs/cgroup/cpu,cpuacct/p2///cpu.* ) and create a service limit metric instead?
> > We can then leverage that as both a new metric and a max value for each launchable.
> 
> We could do that, but I'm wondering if the additional complexity is worth it. Adding a new metric won't be useful unless we then update all of the detectors that attempt to look at the cpu limit of a launchable. If instead we just fix the metric that everyone is already using, we won't have to update any detectors and they will start working as expected.

Yea, this tool isn't really structured specific to our format, so what I suggested doesn't make much sense anyways.  Your approach is more generic for everyone.

**Review by akutta — APPROVED** [review]

**Comment by michaelfinch** [comment]
@akutta thanks for the review. I also figured out how to add a test, and added instruction on how to run it on a Mac.

**Pull request merged**
